#! /usr/bin/perl -w
use strict;
use Text::Markdown 'markdown';
use Getopt::Long;

exit main();

sub main {
	my $filename = $ARGV[0];

	open(my $IN, '<', $filename)
		or die "Error: Unable to read $filename: $!\n";
	local $/;
	my $body = <$IN>;
	close $IN;

	my($title) = ($body =~ /^(.*)\s*\n\s*--*\s*\n/);
	if(not defined $title) {
		die "Error: Could not find title name in $filename.\n";
	}
	$title =~ s/&/&amp;/g;
	$title =~ s/</&lt;/g;
	$title =~ s/>/&gt;/g;

	# Smart quotes
	# Disabled because it trashes code.
	#$body =~ s/(\s)"(.*?)"(\s)/$1“$2”$3/g;

	my $hbody = markdown($body);

	my $project_title = "TIS-100 Hacker's Guide";

	print <<END;
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>$title - $project_title</title>
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,700italic|Michroma|Roboto+Mono:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="index.css" type="text/css">
</head>
<body>

<h1><a href="index.html">$project_title</a></h1>

$hbody

<div class="copyright">
<h2>Acknowledgments</h2>
<p><a href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="float:right" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>
Copyright 2015 Alan De Smet.
This work is licensed under a <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
<a href="https://github.com/AlanDeSmet/TIS-100-Hackers-Guide">Fork this on GitHub!</a></p>
</div>

</body>
</html>
END

	return 0;
}
