#! /usr/bin/perl -w
use strict;
use Text::Markdown 'markdown';
use Getopt::Long;

exit main();

sub main {
	my $filename = $ARGV[0];

	open(my $IN, '<', $filename)
		or die "Error: Unable to read $filename: $!\n";
	local $/;
	my $body = <$IN>;
	close $IN;

	my($title) = ($body =~ /^(.*)\s*\n\s*==*\s*\n/);
	if(not defined $title) {
		die "Error: Could not find title name in $filename.\n";
	}
	$title =~ s/&/&amp;/g;
	$title =~ s/</&lt;/g;
	$title =~ s/>/&gt;/g;

	$body =~ s/(\s)"(.*?)"(\s)/$1“$2”$3/g;

	my $hbody = markdown($body);

	print <<END;
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>$title</title>
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,700italic|Michroma|Roboto+Mono:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="index.css" type="text/css">
</head>
<body>
$hbody
</body>
</html>
END

	return 0;
}
